### ISSUE TITLE
get_elapsed_time

### ISSUE THREAD

**Issue by ambs** [bessarabov/Time-ETA#15]
Hi,
Given you already have a function to format time, why not make it available as well for the complete elapsed time?

Thanks. Love your module ;)

**Comment by bessarabov** [comment]
I'm happy that you love this module =)

Thank you for this idea — I've added new method get_elapsed_time() in https://github.com/bessarabov/Time-ETA/commit/c9a122df5c0e41da2fd26a1cd42af3dfc96feaa8 and released version 1.2.0 with this change (it is on its way to CPAN),

**Comment by ambs** [comment]
yay \o/ thanks
